#include<iostream>
using namespace std;
main(){
string name;
float priceOfAdult , priceOfChild , n1 , n2 , finalPrice , totalMoney ;
float charity , donate, f;
cout<<"Enter Name Of Movie : ";
cin>>name;
cout<<"Enter Price Of Adult Ticket : ";
cin>>priceOfAdult;
cout<<"Enter Price Of Child Ticket : ";
cin>>priceOfChild;
cout<<" Number of Adult Ticket Sold : ";
cin>>n1;
cout<<" Number of Child Ticket Sold : ";
cin>>n2;
cout<<" Enter the percentage of the amount to be donated : ";
cin>>charity;
totalMoney=(priceOfAdult*n1) + (priceOfChild*n2);
donate = (charity*totalMoney)/100;
f=totalMoney-donate;
cout<<"Movie: "<<name<<endl;
cout<<"Total amount generated by ticket sale : "<<totalMoney<<endl;
cout<<"Donated to charity "<<charity<<"% :" <<donate<<endl;
cout<<"Remaining Amount After Donation : "<<f<<endls;
}


