#include<iostream>
using namespace std;
main(){
system("Color F0");
cout<<"                                      ####                            "<<endl;
cout<<"                                    ##    ##                          "<<endl;
cout<<"                                    ########                           "<<endl;
cout<< "                                   ##    ##                           "<<endl;
cout<<"                                    ##    ##                           "<<endl;
cout<<"                                    ##    ##                           "<<endl;
cout<<""<<endl;
cout<<""<<endl;
cout<<""<<endl;
cout<<""<<endl;
cout<<"                                                                                      "<<endl;                                          
cout<<"                                      ##   ##                                          "<<endl;    
cout<<"                                      ##   ##                                        "<<endl;  
cout<<"                                      ####                                           "<<endl;                                   
cout<<"                                      ##                                            "<<endl; 
cout<<"                                      ####                                          "<<endl; 
cout<<"                                      ##   ##                                      "<<endl;      
cout<<"                                      ##   ##                                     "<<endl;     
cout<<"                                                                                 "<<endl; 
cout<<"                                                                              "<<endl; 
cout<<"                                                                             "<<endl; 
cout<<"                                                                             "<<endl; 
cout<<"                                        #######                               "<<endl; 
cout<<"                                            ##                                "<<endl; 
cout<<"                                           ##                                 "<<endl; 
cout<<"                                          ##                                    "<<endl;                    
cout<<"                                         ##                             "<<endl;                                    
cout<<"                                        ##                                 "<<endl; 
cout<<"                                       ########                          "<<endl; 
cout<<"                                                                        "<<endl; 
cout<<"                                                                       "<<endl; 
cout<<"                                                                "<<endl; 
cout<<"                                                                "<<endl; 
cout<<"                                        ##   ##                   "<<endl; 
cout<<"                                        ##   ##                  "<<endl; 
cout<<"                                        ####                      "<<endl; 
cout<<"                                        ##                         "<<endl; 
cout<<"                                        ####                        "<<endl; 
cout<<"                                        ##   ##                      "<<endl; 
cout<<"                                        ##   ##                       "<<endl; 
cout<<"                                                                      "<<endl; 
cout<<"                                                                       "<<endl; 
cout<<"                                                                       "<<endl; 
cout<<"                                                                         "<<endl; 
cout<<"                                                                     "<<endl; 
cout<<"                                          ####                       "<<endl; 
cout<<"                                         ##   ##                     "<<endl; 
cout<<"                                         ##                          "<<endl; 
cout<<"                                          #####                      "<<endl; 
cout<<"                                              ##                     "<<endl; 
cout<<"                                         ##   ##                     "<<endl; 
cout<<"                                          #####                      "<<endl;
}